spring:
  application:
    name: fleet-management

  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.security: INFO
    org.springframework.mail: INFO
    jakarta.mail: INFO


server:
  port: 8080

app:
  upload:
    dir: uploads

  base-url: http://localhost:8080